version: '2'
services:
    mysql:
        build: ./infra/mysql
        ports:
          - "3306:3306"
        volumes:
          - ./infra/mysql/mysql-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: education
        command: "--innodb_use_native_aio=0"
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
        - "80:80"
        - "443:443"
    app:
        build:
            context: infra/app
            dockerfile: Dockerfile
        volumes:
          - ./:/var/www
        links:
          - mysql
    maildev:
        image: kanemu/maildev-with-iconv
        ports:
          - "1080:80"
          - "3025:25"